# importando a biblioteca
import pytholog as pl

new_kb = pl.KnowledgeBase("base")
new_kb(["cd(Ten,PearlJam,Epic,1991)",
"cd(NeverMind,Nirvana,VirginSongs,1992)",
"músico_banda(JeffAment,PearlJam)",
"músico_banda(JeffAment,PearlJam)",
"músico_banda(StoneGossard,PearlJam)",
"músico_banda(JackIrons,PearlJam)",
"músico_banda(MikeMcCready,PearlJam)",
"músico_banda(EddieVedder,PearlJam)",
"músico_banda(KurtCobain,Nirvana)",
"músico_banda(DavidGrohl,Nirvana)",
"músico_banda(ChrisNovoselic,Nirvana)",
"músico_instrumento(JeffAment,Bass)",
"músico_instrumento(JeffAment,Vocals)",
"músico_instrumento(StoneGossard,Guitar)",
"músico_instrumento(StoneGossard,Vocals)",
"músico_instrumento(JackIrons,Drums)",
"músico_instrumento(JackIrons,Percussion)",
"músico_instrumento(MikeMcCready,Guitar)",
"músico_instrumento(EddieVedder,Vocals)",
"músico_instrumento(EddieVedder,Guitar)",
"músico_instrumento(EddieVedder,Guitar)",
"músico_instrumento(KurtCobain,Guitar)",
"músico_instrumento(DavidGrohl,Drums)",
"músico_instrumento(DavidGrohl,Vocals)",
"músico_instrumento(ChrisNovoselic,Bass)",
"músico_instrumento(ChrisNovoselic,Vocals)",
"cd_música(Ten,Once)",
"cd_música(Ten,EvenFlow)",
"cd_música(Ten,Alive)",
"cd_música(Ten,WhyGo)",
"cd_música(Ten,Black)",
"cd_música(Ten,Jeremy)",
"cd_música(Ten,Oceans)",
"cd_música(Ten,Porch)",
"cd_música(Ten,Garden)",
"cd_música(Ten,Deep)",
"cd_música(NiverMind,SmellsLikeTeenSpirits)",
"cd_música(NiverMind,InBloom)",
"cd_música(NiverMind,Breed)",
"cd_música(NiverMind,Lithium)",
"cd_música(NiverMind,Polly)",
"cd_música(NiverMind,TerritorialPissings)",
"cd_música(NiverMind,DrainYou)",
"cd_música(NiverMind,LougueAct)",
"cd_música(NiverMind,StayAway)",
"cd_música(NiverMind,OnAPlain)",
"cd_música(NiverMind,SomethingInTheWay)"])


querys = new_kb.query(pl.Expr("cd_música(X,Deep)"))
print(querys)